using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Networking;
using Newtonsoft.Json;

namespace BreezeSdk.BreezeDemo
{
    public class CreateOrderInput
    {
        public string ProductId { get; set; }
        public int Quantity { get; set; }
        public string Context { get; set; }
    }

    public class CreateOrderResult
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("data")]
        public OrderData Data { get; set; }
    }

    public class OrderData
    {
        [JsonProperty("url")]
        public string Url { get; set; }
    }

    public class YourGameClient : MonoBehaviour
    {
        private const string GameApiUrl = "https://your-game-server-api-endpoint.local";
        private const string CreateOrderPath = "/v1/orders";

        public static string GenerateOrderId()
        {
            return $"order-yourgame-{DateTime.Now:yyyyMMdd-HHmmss}-{Guid.NewGuid().ToString("N")}";
        }

        public async Awaitable<CreateOrderResult> CreateOrderAsync(CreateOrderInput order)
        {
            // NOTE: the order id should be generated by your game server
            string gameOrderId = GenerateOrderId();
            CreateOrderApiRequest request = new()
            {
                LineItems = new List<LineItem>() {
                new() {
                    Product = order.ProductId,
                    Quantity = order.Quantity
                }
            },
                BillingEmail = "customer@example.com",
                ClientReferenceId = gameOrderId,
                SuccessReturnUrl = "breezedemo://breeze-payment/purchase/success",
                FailReturnUrl = "breezedemo://breeze-payment/purchase/failure",
                Customer = new CustomerReference()
                {
                    ReferenceId = "user-superapp-test1"
                },
                Context = order.Context
            };
            string jsonPayload;
            try
            {
                Debug.Log($"[GameClient] creating order request...");
                jsonPayload = JsonConvert.SerializeObject(request);
                Debug.Log($"[GameClient] create order request: {jsonPayload}");
            }
            catch (Exception ex)
            {
                Debug.LogError($"[GameClient] serialize request exception: {ex}");
                return null;
            }

            CreateOrderResult result = await SendOrderAsync(jsonPayload);
            return result;
        }

        private async Awaitable<CreateOrderResult> SendOrderAsync(string jsonPayload)
        {
            string apiUrl = GameApiUrl + CreateOrderPath;
            using (var request = new UnityWebRequest(apiUrl, "POST"))
            {
                byte[] bodyRaw = System.Text.Encoding.UTF8.GetBytes(jsonPayload);
                request.uploadHandler = new UploadHandlerRaw(bodyRaw);
                request.downloadHandler = new DownloadHandlerBuffer();
                request.SetRequestHeader("Content-Type", "application/json");

                await request.SendWebRequest();

                if (request.result == UnityWebRequest.Result.Success)
                {
                    string jsonText = request.downloadHandler.text;
                    Debug.Log($"[GameClient] Order created. Response: {jsonText}");
                    CreateOrderResult result = null;
                    try
                    {
                        result = JsonConvert.DeserializeObject<CreateOrderResult>(jsonText);
                    }
                    catch (Exception ex)
                    {
                        Debug.LogError($"[GameClient] deserialize response exception: {ex}");
                    }
                    return result;
                }
                else
                {
                    Debug.LogError($"[GameClient] Order failed: {request.error} | Response: {request.downloadHandler?.text}");
                    return null;
                }
            }
        }
    }

    class CreateOrderApiRequest
    {
        [JsonProperty("lineItems")]
        public List<LineItem> LineItems { get; set; }

        [JsonProperty("billingEmail")]
        public string BillingEmail { get; set; }

        [JsonProperty("clientReferenceId")]
        public string ClientReferenceId { get; set; }

        [JsonProperty("successReturnUrl")]
        public string SuccessReturnUrl { get; set; }

        [JsonProperty("failReturnUrl")]
        public string FailReturnUrl { get; set; }

        [JsonProperty("customer")]
        public CustomerReference Customer { get; set; }

        [JsonProperty("context", NullValueHandling = NullValueHandling.Ignore)]
        public string Context { get; set; }
    }

    class LineItem
    {
        [JsonProperty("product")]
        public string Product { get; set; }

        [JsonProperty("quantity")]
        public int Quantity { get; set; }
    }

    class CustomerReference
    {
        [JsonProperty("referenceId")]
        public string ReferenceId { get; set; }
    }
}